on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  my_job:
    name: Running on Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          pip install -r requirements.txt
      - name: Install dependencies on Ubuntu
        if: runner.os == 'windows'
        run: |
          pip install -r requirements.txt
      - name: Generate ASCII Art
        run: |
          python -c "import pyfiglet; ascii_art = pyfiglet.figlet_format('Happy New Year'); print(ascii_art)"
